# Generated by Django 4.2.7 on 2025-06-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='equipo_padre',
        ),
        migrations.CreateModel(
            name='EquipoAsociado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=300, verbose_name='Codigo')),
                ('equipo', models.CharField(max_length=300, verbose_name='Equipo')),
                ('descripcion', models.TextField(verbose_name='Descripcion')),
                ('equipoAsociado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calidad.equipos', verbose_name='Equipo Asociado')),
            ],
            options={
                'verbose_name': 'Equipo asociado',
                'verbose_name_plural': 'Equipos asociados',
            },
        ),
    ]
