# Generated by Django 4.2.7 on 2025-06-04 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_remove_equipos_equipo_padre_equipoasociado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipoasociado',
            name='equipoAsociado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.equipos', verbose_name='Equipo Asociado'),
        ),
    ]
