# Generated by Django 4.2.7 on 2025-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_alter_equipoasociado_equipoasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='estadoCalibracion',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Calibrado'), ('2', 'Calibración caducada'), ('3', 'Solicitado presupuesto'), ('4', 'Calibración en curso'), ('5', 'Esperando certificado'), ('6', 'Esperando actualización de la ficha del equipo'), ('7', 'Verificación al uso')], default='0', max_length=10, verbose_name='Estado Calibración'),
        ),
        migrations.AddField(
            model_name='equipos',
            name='tipoCalibracion',
            field=models.CharField(choices=[('1', 'Calibración interna'), ('2', 'Calibración externa')], default='1', max_length=10, verbose_name='Tipo Calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaCaducidadCalibracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha próxima calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaCalibracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Calibración'),
        ),
    ]
