# Generated by Django 4.2.7 on 2025-08-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_alter_equipoasociado_equipoasociado'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='estadoCalibracion',
            field=models.CharField(choices=[('0', 'Calibrado'), ('1', 'Necesita calibración'), ('2', 'Solicitado presupuesto'), ('3', 'Calibración en curso'), ('4', 'Esperando certificado'), ('5', 'Esperando actualización de la ficha del equipo')], default='0', max_length=10),
        ),
        migrations.AddField(
            model_name='equipos',
            name='tipoCalibracion',
            field=models.CharField(choices=[('1', 'Calibración interna'), ('2', 'Calibración externa')], default='1', max_length=10),
        ),
    ]
