# Generated by Django 4.2.7 on 2025-09-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_equipos_estadocalibracion_equipos_tipocalibracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaCaducidadCalibracion',
            field=models.DateField(blank=True, default='2025-09-25', null=True, verbose_name='Fecha próxima calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaCalibracion',
            field=models.DateField(blank=True, default='2025-09-25', null=True, verbose_name='Fecha de Calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='tipoCalibracion',
            field=models.CharField(choices=[('0', 'No requiere'), ('1', 'Calibración interna'), ('2', 'Calibración externa')], default='0', max_length=10, verbose_name='Tipo Calibración'),
        ),
    ]
