# Generated by Django 4.2.7 on 2025-08-19 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0004_equipos_estadocalibracion_equipos_tipocalibracion'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='tipoEquipo',
            field=models.CharField(choices=[('0', 'Controlado'), ('1', 'No controlado')], default='0', max_length=10, verbose_name='Tipo equipo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='equipos',
            name='estadoCalibracion',
            field=models.CharField(choices=[('0', 'Calibrado'), ('1', 'Necesita calibración'), ('2', 'Solicitado presupuesto'), ('3', 'Calibración en curso'), ('4', 'Esperando certificado'), ('5', 'Esperando actualización de la ficha del equipo')], default='0', max_length=10, verbose_name='Estado Calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='tipoCalibracion',
            field=models.CharField(choices=[('1', 'Calibración interna'), ('2', 'Calibración externa')], default='1', max_length=10, verbose_name='Tipo Calibración'),
        ),
    ]
