# Generated by Django 4.2.7 on 2025-09-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_alter_equipos_fechacaducidadcalibracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaCaducidadCalibracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha próxima calibración'),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaCalibracion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Calibración'),
        ),
    ]
