# Generated by Django 4.2.7 on 2025-08-19 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0005_equipos_tipoequipo_alter_equipos_estadocalibracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='tipoEquipo',
            field=models.CharField(choices=[('0', 'Controlado'), ('1', 'No controlado')], default='0', max_length=10, verbose_name='Tipo equipo'),
        ),
    ]
