# Generated by Django 4.2.7 on 2025-08-19 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0006_alter_equipos_tipoequipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipos',
            name='tipoEquipo',
        ),
    ]
