# Generated by Django 4.2.7 on 2026-02-26 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0006_alter_equipos_fechacaducidadcalibracion_and_more'),  # <-- aquí pon el nombre real
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='fechaCalibracion',
            field=models.DateField(
                verbose_name="Fecha de Calibración",
                null=True,
                blank=True,
            ),
        ),
        migrations.AlterField(
            model_name='equipos',
            name='fechaCaducidadCalibracion',
            field=models.DateField(
                verbose_name="Fecha próxima calibración",
                null=True,
                blank=True,
            ),
        ),
    ]
