# Generated by Django 4.2.7 on 2025-08-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_remove_equipos_tipoequipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipos',
            name='estadoCalibracion',
            field=models.CharField(choices=[('0', 'Calibrado'), ('1', 'Calibración caducada'), ('2', 'Solicitado presupuesto'), ('3', 'Calibración en curso'), ('4', 'Esperando certificado'), ('5', 'Esperando actualización de la ficha del equipo'), ('6', 'Verificación al uso')], default='0', max_length=10, verbose_name='Estado Calibración'),
        ),
    ]
