# Generated by Django 4.2.7 on 2026-05-28 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_auto_20260226_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='yearCompra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Año de compra'),
        ),
    ]
