# Generated by Django 4.2.7 on 2025-03-17 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tratamiento',
            name='valorTamiz',
        ),
    ]
