# Generated by Django 4.2.7 on 2025-04-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humedad',
            name='fecha',
        ),
        migrations.AddField(
            model_name='humedad',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Fin'),
        ),
        migrations.AddField(
            model_name='humedad',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
