# Generated by Django 4.1 on 2024-01-26 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_resultados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='humedad',
            name='manual',
        ),
        migrations.RemoveField(
            model_name='humedad',
            name='resultado',
        ),
        migrations.AlterField(
            model_name='humedad',
            name='criterio',
            field=models.CharField(default='5', max_length=50, verbose_name='Criterio'),
        ),
    ]
