# Generated by Django 4.2.7 on 2025-04-04 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_remove_humedad_fecha_humedad_fechafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='granulometria',
            name='fecha',
        ),
        migrations.AddField(
            model_name='granulometria',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='FechaInicio'),
        ),
    ]
