# Generated by Django 4.2.7 on 2024-05-25 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0002_alter_humedad_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kmax',
            name='ensayo',
        ),
        migrations.RemoveField(
            model_name='kmax',
            name='equipos',
        ),
        migrations.RemoveField(
            model_name='kmax',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='kmax',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='ensayo',
        ),
        migrations.RemoveField(
            model_name='resultados',
            name='muestra',
        ),
        migrations.RemoveField(
            model_name='resultadosdpdt',
            name='ensayo',
        ),
        migrations.RemoveField(
            model_name='resultadoskmax',
            name='ensayo',
        ),
        migrations.RemoveField(
            model_name='granulometria',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='n1',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='n2',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='n4',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='o1',
            name='resultado',
        ),
        migrations.RemoveField(
            model_name='pmax',
            name='resultado',
        ),
        migrations.AddField(
            model_name='clo',
            name='unidad',
            field=models.CharField(default='%', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='emi',
            name='unidad',
            field=models.CharField(default='mJ', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='d10',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='d10'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='d50',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='d50'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='d90',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True, verbose_name='d50'),
        ),
        migrations.AddField(
            model_name='granulometria',
            name='unidad',
            field=models.CharField(default='um', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='humedad',
            name='unidad',
            field=models.CharField(default='%', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='lie',
            name='unidad',
            field=models.CharField(default='g/m3', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='dpdt',
            field=models.IntegerField(null=True, verbose_name='dPdT'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='kmax',
            field=models.IntegerField(null=True, verbose_name='kmax'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='pmax',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Pmax'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='unidadDpdt',
            field=models.CharField(default='bar/s', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='unidadPmax',
            field=models.CharField(default='bar', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='rec',
            name='unidad',
            field=models.CharField(default='Mohm', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='tmic',
            name='unidad',
            field=models.CharField(default='ºC', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='tmin',
            name='unidad',
            field=models.CharField(default='ºC', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='resultado',
            field=models.IntegerField(null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='humedad',
            field=models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='resultado',
            field=models.IntegerField(null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=12, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='resultado',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Resultado'),
        ),
        migrations.DeleteModel(
            name='dPdT',
        ),
        migrations.DeleteModel(
            name='Kmax',
        ),
        migrations.DeleteModel(
            name='Resultados',
        ),
        migrations.DeleteModel(
            name='ResultadosdPdT',
        ),
        migrations.DeleteModel(
            name='ResultadosKmax',
        ),
    ]
