# Generated by Django 4.2.7 on 2025-04-04 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0003_remove_granulometria_fecha_granulometria_fechafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tmic',
            name='fecha',
        ),
        migrations.AddField(
            model_name='tmic',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='tmic',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='FechaInicio'),
        ),
    ]
