# Generated by Django 4.2.7 on 2024-05-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0004_alter_humedad_temperaturaambiente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedad',
            name='criterio',
            field=models.CharField(blank=True, default='5', max_length=50, null=True, verbose_name='Criterio'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='desviacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Desviación'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='equipos',
            field=models.ManyToManyField(blank=True, null=True, to='ensayos.equipos', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='fechaAuto',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha automática'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='fechaRev',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha revisión'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observación'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='tDesecacion',
            field=models.IntegerField(blank=True, default=105, null=True, verbose_name='Temperatura de Desecación'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='unidad',
            field=models.CharField(blank=True, default='%', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
