# Generated by Django 4.2.4 on 2024-01-29 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0004_alter_humedad_tiempoensayo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoshumedad',
            name='observacion',
        ),
        migrations.AddField(
            model_name='humedad',
            name='observacion',
            field=models.CharField(default='nulos', max_length=1000, verbose_name='Observación'),
            preserve_default=False,
        ),
    ]
