# Generated by Django 4.2.4 on 2024-01-31 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0015_rename_tamaño_descripcionmuestra_tamano'),
        ('ensayos', '0005_remove_resultadoshumedad_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='ensayos',
            field=models.ManyToManyField(to='muestras.listaensayos', verbose_name='Ensayos'),
        ),
    ]
