# Generated by Django 4.2.7 on 2024-07-09 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0005_alter_humedad_criterio_alter_humedad_desviacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granulometria',
            name='d10',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='d10'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='d50',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='d50'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='d90',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='d50'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='equipos',
            field=models.ManyToManyField(blank=True, null=True, to='ensayos.equipos', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='fechaAuto',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha automática'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='fechaRev',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha revisión'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='tiempoEnsayo',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5, null=True, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='unidad',
            field=models.CharField(blank=True, default='um', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
