# Generated by Django 4.2.7 on 2025-04-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0005_remove_tmin_fecha_tmin_fechafin_tmin_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lie',
            name='fecha',
        ),
        migrations.AddField(
            model_name='lie',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='lie',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
