# Generated by Django 4.2.7 on 2024-07-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0006_alter_granulometria_d10_alter_granulometria_d50_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='granulometria',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='d50'),
        ),
    ]
