# Generated by Django 4.2.4 on 2024-01-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0006_equipos_ensayos'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipos',
            name='codigo',
            field=models.CharField(default='null', max_length=300, verbose_name='Codigo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipos',
            name='descripcion',
            field=models.TextField(default='null', verbose_name='Descripcion'),
            preserve_default=False,
        ),
    ]
