# Generated by Django 4.2.7 on 2025-04-07 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0007_remove_emi_fecha_emi_fechafin_emi_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emisin',
            name='fecha',
        ),
        migrations.AddField(
            model_name='emisin',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='emisin',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='inductancia',
            field=models.CharField(blank=True, choices=[('1', 'SI'), ('2', 'NO')], default='1', max_length=100, null=True, verbose_name='Inductancia'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='inductancia',
            field=models.CharField(blank=True, choices=[('1', 'SI'), ('2', 'NO')], default='2', max_length=100, null=True, verbose_name='Inductancia'),
        ),
    ]
