# Generated by Django 4.2.7 on 2024-07-09 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0007_granulometria_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='granulometria',
            name='via',
            field=models.CharField(blank=True, choices=[('1', 'Seca'), ('2', 'Húmeda')], max_length=100, null=True, verbose_name='Vía'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='d90',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='d90'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='equipos',
            field=models.ManyToManyField(to='ensayos.equipos', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='equipos',
            field=models.ManyToManyField(to='ensayos.equipos', verbose_name='Equipos'),
        ),
    ]
