# Generated by Django 4.2.7 on 2024-07-22 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0009_resultadostmic_tiempoensayo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tmic',
            name='funde',
            field=models.CharField(default='', max_length=50, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoEnsayo',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tiempo ensayo'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoTmax',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Tiempo a temperatura máxima'),
        ),
    ]
