# Generated by Django 4.2.7 on 2024-07-22 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0011_alter_tmic_funde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmic',
            name='funde',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO')], default='2', max_length=50, verbose_name='Funde'),
        ),
    ]
