# Generated by Django 4.2.7 on 2025-04-07 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0011_remove_clo_fecha_clo_fechafin_clo_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='fecha',
        ),
        migrations.AddField(
            model_name='rec',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='rec',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
