# Generated by Django 4.2.7 on 2024-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0012_alter_tmic_funde'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadostmic',
            name='observacion',
        ),
        migrations.AddField(
            model_name='tmic',
            name='observacion',
            field=models.CharField(blank=True, default='null', max_length=1000, null=True, verbose_name='Observacion'),
        ),
    ]
