# Generated by Django 4.2.7 on 2025-04-07 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0012_remove_rec_fecha_rec_fechafin_rec_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='unidad',
            field=models.CharField(blank=True, default='ohm·m', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
