# Generated by Django 4.2.7 on 2025-04-08 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0013_alter_rec_unidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosrec',
            name='nPrueba',
            field=models.CharField(choices=[('', 'Selecciona'), ('1', '1'), ('2', '2')], default='null', max_length=50, verbose_name='Numero Prueba'),
            preserve_default=False,
        ),
    ]
