# Generated by Django 4.2.7 on 2024-08-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0013_remove_resultadostmic_observacion_tmic_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadostmic',
            old_name='tiempoEnsayo',
            new_name='tiempoPrueba',
        ),
        migrations.AddField(
            model_name='tmic',
            name='tiempoMaxEnsayo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo máximo del ensayo'),
        ),
    ]
