# Generated by Django 4.2.7 on 2024-08-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0014_rename_tiempoensayo_resultadostmic_tiempoprueba_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmic',
            name='equipos',
            field=models.ManyToManyField(blank=True, null=True, to='ensayos.equipos', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='fechaAuto',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha automática'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='fechaRev',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha revisión'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='funde',
            field=models.CharField(blank=True, choices=[('1', 'SI'), ('2', 'NO')], default='2', max_length=50, null=True, verbose_name='Funde'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='tiempoEnsayo',
            field=models.DecimalField(blank=True, decimal_places=2, default=5, max_digits=5, null=True, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='unidad',
            field=models.CharField(blank=True, default='ºC', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
