# Generated by Django 4.2.7 on 2025-04-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0014_resultadosrec_nprueba'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n1',
            name='fecha',
        ),
        migrations.AddField(
            model_name='n1',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='n1',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
