# Generated by Django 4.2.7 on 2025-04-10 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0015_remove_n1_fecha_n1_fechafin_n1_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n2',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='n2',
            name='fechaAuto',
        ),
        migrations.AddField(
            model_name='n2',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='n2',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
