# Generated by Django 4.2.7 on 2025-04-10 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0016_remove_n2_fecha_remove_n2_fechaauto_n2_fechafin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n4',
            name='fecha',
        ),
        migrations.AddField(
            model_name='n4',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='n4',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
