# Generated by Django 4.2.7 on 2024-08-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0017_rename_tiempoensayo_tmin_horasensayo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmic',
            name='equipos',
            field=models.ManyToManyField(to='ensayos.equipos', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='fechaAuto',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Fecha automática'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='fechaRev',
            field=models.DateField(auto_now=True, null=True, verbose_name='Fecha revisión'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='unidad',
            field=models.CharField(blank=True, default='ºC', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
