# Generated by Django 4.2.7 on 2025-04-10 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0017_remove_n4_fecha_n4_fechafin_n4_fechainicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='o1',
            name='fecha',
        ),
        migrations.AddField(
            model_name='o1',
            name='fechaFin',
            field=models.DateField(blank=True, null=True, verbose_name='FechaFin'),
        ),
        migrations.AddField(
            model_name='o1',
            name='fechaInicio',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
    ]
