# Generated by Django 4.2.7 on 2025-04-11 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0018_remove_o1_fecha_o1_fechafin_o1_fechainicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosn1',
            name='tiempo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo'),
        ),
    ]
