# Generated by Django 4.2.7 on 2024-08-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0019_remove_lie_tiempoensayo_lie_horasensayo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoslie',
            name='observacion',
        ),
        migrations.AddField(
            model_name='lie',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
    ]
