# Generated by Django 4.2.7 on 2024-08-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0020_remove_resultadoslie_observacion_lie_observacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clo',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RenameField(
            model_name='emi',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RenameField(
            model_name='n2',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RenameField(
            model_name='n4',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RenameField(
            model_name='o1',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RenameField(
            model_name='pmax',
            old_name='tiempoEnsayo',
            new_name='horasEnsayo',
        ),
        migrations.RemoveField(
            model_name='n1',
            name='tiempoEnsayo',
        ),
        migrations.RemoveField(
            model_name='rec',
            name='tiempoEnsayo',
        ),
        migrations.RemoveField(
            model_name='resultadosclo',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadosemi',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadosn1',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadosn2',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadosn4',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadoso1',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadospmax',
            name='observacion',
        ),
        migrations.RemoveField(
            model_name='resultadosrec',
            name='observacion',
        ),
        migrations.AddField(
            model_name='clo',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emi',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n1',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AddField(
            model_name='n1',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n2',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n4',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='o1',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pmax',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rec',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AddField(
            model_name='rec',
            name='observacion',
            field=models.CharField(default='null', max_length=1000, verbose_name='Observacion'),
            preserve_default=False,
        ),
    ]
