# Generated by Django 4.2.7 on 2025-04-19 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0021_alter_clo_usuario_alter_emi_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=4, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=2, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AlterField(
            model_name='n1',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
    ]
