# Generated by Django 4.2.7 on 2024-08-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0021_rename_tiempoensayo_clo_horasensayo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emi',
            name='inductancia',
            field=models.CharField(choices=[('1', 'SI'), ('2', 'NO')], default='null', max_length=100, verbose_name='Inductancia'),
            preserve_default=False,
        ),
    ]
