# Generated by Django 4.2.7 on 2025-04-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0022_alter_clo_horasensayo_alter_lie_horasensayo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lie',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
    ]
