# Generated by Django 4.2.7 on 2024-08-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0023_alter_emi_fecha_alter_emi_fechaauto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadospmax',
            name='pex',
        ),
    ]
