# Generated by Django 4.2.7 on 2025-04-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0023_alter_lie_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humedad',
            name='criterio',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('manual', 'Manual')], default='5', max_length=50, null=True, verbose_name='Criterio'),
        ),
    ]
