# Generated by Django 4.2.7 on 2024-08-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0024_remove_resultadospmax_pex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmax',
            name='boquilla',
            field=models.CharField(blank=True, choices=[('1', 'rebote'), ('2', 'tubular')], max_length=300, null=True, verbose_name='Boquilla'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'simex'), ('2', 'sobbe')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='dpdt',
            field=models.IntegerField(blank=True, null=True, verbose_name='dPdT'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='kmax',
            field=models.IntegerField(blank=True, null=True, verbose_name='kmax'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='pmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Pmax'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='unidadDpdt',
            field=models.CharField(blank=True, default='bar/s', max_length=50, null=True, verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='unidadPmax',
            field=models.CharField(blank=True, default='bar', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
