# Generated by Django 4.2.7 on 2025-04-29 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0025_tmic_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='rec',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AddField(
            model_name='tmin',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión'),
        ),
    ]
