# Generated by Django 4.2.7 on 2024-08-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0025_alter_pmax_boquilla_alter_pmax_cerillas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pmax',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
    ]
