# Generated by Django 4.2.7 on 2024-08-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0026_alter_pmax_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadospmax',
            name='dpdt',
            field=models.IntegerField(verbose_name='dP/dT'),
        ),
    ]
