# Generated by Django 4.2.7 on 2025-04-29 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0026_rec_presion_tmin_presion'),
    ]

    operations = [
        migrations.AddField(
            model_name='clo',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AddField(
            model_name='lie',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AddField(
            model_name='pmax',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
    ]
