# Generated by Django 4.2.7 on 2025-05-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0027_clo_temperaturaesfera_lie_temperaturaesfera_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadostmin',
            name='repeticiones',
            field=models.IntegerField(default=0, verbose_name='Repeticiones'),
            preserve_default=False,
        ),
    ]
