# Generated by Django 4.2.7 on 2024-08-28 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0027_alter_resultadospmax_dpdt'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadosclo',
            name='oxigeno',
            field=models.IntegerField(default=0, verbose_name='Oxígeno'),
            preserve_default=False,
        ),
    ]
