# Generated by Django 4.2.7 on 2024-08-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0028_resultadosclo_oxigeno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='boquilla',
            field=models.CharField(blank=True, choices=[('1', 'rebote'), ('2', 'tubular')], max_length=300, null=True, verbose_name='Boquilla'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'simex'), ('2', 'sobbe')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='resultado',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='unidad',
            field=models.CharField(blank=True, default='%', max_length=50, null=True, verbose_name='Unidad'),
        ),
    ]
