# Generated by Django 4.2.7 on 2025-05-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0028_resultadostmin_repeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadostmin',
            name='repeticiones',
            field=models.IntegerField(blank=True, null=True, verbose_name='Repeticiones'),
        ),
    ]
