# Generated by Django 4.2.7 on 2024-08-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0029_alter_clo_boquilla_alter_clo_cerillas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmic',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado'),
        ),
    ]
