# Generated by Django 4.2.7 on 2025-05-29 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0029_alter_resultadostmin_repeticiones'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosclo',
            name='concentracion',
            field=models.IntegerField(verbose_name='Concentración'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='concentracion',
            field=models.IntegerField(verbose_name='Concentración'),
        ),
    ]
