# Generated by Django 4.2.7 on 2025-05-29 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0030_alter_resultadosclo_concentracion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosclo',
            name='dpdt',
            field=models.IntegerField(verbose_name='dPdT'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='dpdt',
            field=models.IntegerField(verbose_name='dPdT'),
        ),
    ]
