# Generated by Django 4.2.7 on 2024-08-30 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0031_alter_humedad_resultado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tmin',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado'),
        ),
    ]
