# Generated by Django 4.2.7 on 2024-08-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0032_alter_tmin_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lie',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado'),
        ),
    ]
