# Generated by Django 4.2.7 on 2025-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0032_alter_resultadospmax_peso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosrec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Resultado'),
        ),
    ]
