# Generated by Django 4.2.7 on 2025-06-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0033_alter_resultadosrec_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='tratamiento',
            name='tamiz',
            field=models.CharField(blank=True, choices=[('1', 'NO'), ('2', 'SI')], default=None, max_length=500, null=True, verbose_name='Tamiz'),
        ),
    ]
