# Generated by Django 4.2.7 on 2024-08-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0034_alter_emi_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Resultado'),
        ),
    ]
