# Generated by Django 4.2.7 on 2025-06-05 12:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0003_alter_equipoasociado_equipoasociado'),
        ('ensayos', '0034_tratamiento_tamiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tratamiento',
            name='tamiz',
            field=models.ForeignKey(blank=True, default=None, max_length=500, null=True, on_delete=django.db.models.deletion.CASCADE, to='calidad.equipoasociado', verbose_name='Tamiz'),
        ),
    ]
