# Generated by Django 4.2.7 on 2024-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0035_alter_clo_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rec',
            name='ensayoHumedad',
        ),
        migrations.AddField(
            model_name='n1',
            name='resultado',
            field=models.CharField(choices=[('1', 'No se clasifica'), ('2', 'Grupo de embalaje/envasado II/ Categoría 1'), ('3', 'Grupo de embalaje/envasado III/ Categoría 2')], default='null', max_length=100, verbose_name='Resultado'),
            preserve_default=False,
        ),
    ]
