# Generated by Django 4.2.7 on 2025-06-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0035_alter_tratamiento_tamiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='resultadosrec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Resultado'),
        ),
    ]
