# Generated by Django 4.2.7 on 2025-09-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0035_alter_tratamiento_tamiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'sobbe'), ('2', 'simex')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión Ambiente'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='n1',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n1',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='o1',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='o1',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'sobbe'), ('2', 'simex')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso equivalente'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='pex',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PEX'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='pm',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso equivalente'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='pex',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PEX'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='pm',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='resultadospmax',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Peso equivalente'),
        ),
        migrations.AlterField(
            model_name='resultadosrec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True, verbose_name='Resultado'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tPlato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatura plato'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoPrueba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo ensayo'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoTmax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo a temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='resultadostmin',
            name='presion',
            field=models.IntegerField(verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='resultadostmin',
            name='tHorno',
            field=models.IntegerField(verbose_name='Temperatura horno'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='tiempoMaxEnsayo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo máximo del ensayo'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
    ]
