# Generated by Django 4.2.7 on 2025-09-18 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0036_alter_rec_resultado_alter_resultadosrec_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='clo',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión Ambiente'),
        ),
        migrations.AlterField(
            model_name='emi',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión Ambiente'),
        ),
        migrations.AlterField(
            model_name='emisin',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='granulometria',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='humedad',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='lie',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='n1',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n1',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='o1',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='o1',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='temperaturaEsfera',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='rec',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=7, null=True, verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='tmin',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
    ]
