# Generated by Django 4.2.7 on 2025-09-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0036_alter_clo_cerillas_alter_clo_humedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rec',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado'),
        ),
    ]
