# Generated by Django 4.2.7 on 2025-09-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0037_alter_clo_humedad_alter_clo_temperaturaambiente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosclo',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso equivalente'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='pex',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PEX'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='pm',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso equivalente'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='pex',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PEX'),
        ),
        migrations.AlterField(
            model_name='resultadoslie',
            name='pm',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='PM'),
        ),
        migrations.AlterField(
            model_name='resultadospmax',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Peso equivalente'),
        ),
    ]
