# Generated by Django 4.2.7 on 2025-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0037_alter_rec_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosrec',
            name='resultado',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Resultado'),
        ),
    ]
