# Generated by Django 4.2.7 on 2025-09-19 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0038_alter_resultadosclo_peso_alter_resultadosclo_pex_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoshumedad',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Resultado'),
        ),
    ]
