# Generated by Django 4.2.7 on 2026-01-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0038_alter_resultadosrec_resultado'),
    ]

    operations = [
        migrations.AddField(
            model_name='o1',
            name='humedadCelulosa',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='Humedad Celulosa'),
            preserve_default=False,
        ),
    ]
