# Generated by Django 4.2.7 on 2024-09-08 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0039_alter_n1_fecha_alter_n1_humedad_alter_n1_observacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='n2',
            name='resultado',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='n2',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
        migrations.AlterField(
            model_name='resultadosn1',
            name='ensayo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.n1', verbose_name='Ensayo TMIn'),
        ),
    ]
