# Generated by Django 4.2.7 on 2025-09-19 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0039_alter_resultadoshumedad_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadoshumedad',
            name='resultado',
            field=models.CharField(default=0, max_length=100, verbose_name='Resultado'),
            preserve_default=False,
        ),
    ]
