# Generated by Django 4.2.7 on 2026-01-23 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0040_alter_resultadoslie_pex_alter_resultadoslie_pm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o1',
            name='humedadCelulosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True, verbose_name='Humedad Celulosa'),
        ),
    ]
