# Generated by Django 4.2.7 on 2024-09-08 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0040_n2_resultado_alter_n2_fecha_alter_n2_humedad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n2',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', 'No se clasifica'), ('2', 'Grupo de embalaje/ envasado I / Categoría 1')], max_length=100, null=True, verbose_name='resultado'),
        ),
    ]
