# Generated by Django 4.2.7 on 2025-09-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0040_alter_resultadoshumedad_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadostmic',
            name='tPlato',
            field=models.IntegerField(blank=True, null=True, verbose_name='Temperatura plato'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoPrueba',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo ensayo'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoTmax',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo a temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='tmic',
            name='tiempoMaxEnsayo',
            field=models.IntegerField(blank=True, null=True, verbose_name='Tiempo máximo del ensayo'),
        ),
    ]
