# Generated by Django 4.2.7 on 2026-01-27 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0041_alter_o1_humedadcelulosa'),
    ]

    operations = [
        migrations.AddField(
            model_name='o1',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='archivosEvaluacionesFuente'),
        ),
        migrations.AddField(
            model_name='o1',
            name='tamanoMuestra',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, verbose_name='% de muestra < 500 um'),
        ),
    ]
