# Generated by Django 4.2.7 on 2025-09-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0041_alter_resultadostmic_tplato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadostmin',
            name='peso',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='Peso'),
        ),
        migrations.AlterField(
            model_name='resultadostmin',
            name='presion',
            field=models.IntegerField(verbose_name='Presión'),
        ),
        migrations.AlterField(
            model_name='resultadostmin',
            name='tHorno',
            field=models.IntegerField(verbose_name='Temperatura horno'),
        ),
    ]
