# Generated by Django 4.2.7 on 2026-02-23 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0041_alter_o1_humedadcelulosa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosclo',
            name='pex',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PEX'),
        ),
        migrations.AlterField(
            model_name='resultadosclo',
            name='pm',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='PM'),
        ),
    ]
