# Generated by Django 4.2.7 on 2024-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0041_alter_n2_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n4',
            name='celda100',
        ),
        migrations.RemoveField(
            model_name='n4',
            name='celda25',
        ),
        migrations.AddField(
            model_name='n4',
            name='celda',
            field=models.CharField(choices=[('1', '100mm'), ('2', '25mm')], default='null', max_length=100, verbose_name='Celda'),
            preserve_default=False,
        ),
    ]
