# Generated by Django 4.2.7 on 2025-09-19 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0042_alter_resultadostmin_peso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clo',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'sobbe'), ('2', 'simex')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
        migrations.AlterField(
            model_name='pmax',
            name='cerillas',
            field=models.CharField(blank=True, choices=[('1', 'sobbe'), ('2', 'simex')], max_length=300, null=True, verbose_name='Cerillas'),
        ),
    ]
