# Generated by Django 4.2.7 on 2024-09-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0042_remove_n4_celda100_remove_n4_celda25_n4_celda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n4',
            name='celda',
        ),
        migrations.AddField(
            model_name='n4',
            name='celda100',
            field=models.BooleanField(default=0, verbose_name='Celda 100 mm'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='n4',
            name='celda25',
            field=models.BooleanField(default=0, verbose_name='Celda 25 mm'),
            preserve_default=False,
        ),
    ]
