# Generated by Django 4.2.7 on 2026-02-26 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0007_auto_20260226_0929'),
        ('muestras', '0006_alter_descripcionmuestra_empresatransporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ensayos', '0042_alter_resultadosclo_pex_alter_resultadosclo_pm'),
    ]

    operations = [
        migrations.CreateModel(
            name='exploNoExplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaAmbiente', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ambiente')),
                ('temperaturaEsfera', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Esfera')),
                ('humedad', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente')),
                ('cerillas', models.CharField(blank=True, choices=[('1', 'sobbe'), ('2', 'simex')], max_length=300, null=True, verbose_name='Cerillas')),
                ('boquilla', models.CharField(blank=True, choices=[('1', 'rebote'), ('2', 'tubular')], max_length=300, null=True, verbose_name='Boquilla')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='FechaFin')),
                ('fechaAuto', models.DateField(auto_now_add=True, verbose_name='Fecha automática')),
                ('fechaRev', models.DateField(auto_now=True, verbose_name='Fecha revisión')),
                ('pmax', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Pmax')),
                ('dpdt', models.IntegerField(blank=True, null=True, verbose_name='dPdT')),
                ('kmax', models.IntegerField(blank=True, null=True, verbose_name='kmax')),
                ('unidadPmax', models.CharField(blank=True, default='bar', max_length=50, null=True, verbose_name='Unidad')),
                ('unidadDpdt', models.CharField(blank=True, default='bar/s', max_length=50, null=True, verbose_name='Unidad')),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion')),
                ('horasEnsayo', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tiempo de ensayo')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.listaensayos', verbose_name='Ensayo')),
                ('equipos', models.ManyToManyField(to='calidad.equipos', verbose_name='Equipos')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.muestras', verbose_name='Muestra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Pmax',
                'verbose_name_plural': 'Pmaxs',
            },
        ),
        migrations.CreateModel(
            name='ResultadosexploNoExplo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('concentracion', models.IntegerField(verbose_name='Concentración')),
                ('peso', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='Peso equivalente')),
                ('pm', models.DecimalField(decimal_places=1, max_digits=7, verbose_name='PM')),
                ('dpdt', models.IntegerField(verbose_name='dP/dT')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.explonoexplo', verbose_name='Ensayo Explo/No explo')),
            ],
            options={
                'verbose_name': 'Resultado Pmax',
                'verbose_name_plural': 'Resultados Pmaxs',
            },
        ),
    ]
