# Generated by Django 4.2.7 on 2026-06-25 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0008_equipos_yearcompra'),
        ('muestras', '0006_alter_descripcionmuestra_empresatransporte_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ensayos', '0043_explonoexplo_resultadosexplonoexplo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='explonoexplo',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
        migrations.CreateModel(
            name='BZ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaEnsayo', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Temperatura Ensayo')),
                ('humedad', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True, verbose_name='Humedad Ambiente')),
                ('nRepeticiones', models.IntegerField(blank=True, default=10, null=True, verbose_name='Número repeticiones')),
                ('tipoFuenteIgnicion', models.CharField(choices=[('1', 'Llama de gas'), ('2', 'Filamento incandescente')], max_length=100, verbose_name='Tipo de fuente de ignición')),
                ('tiempoFuenteIgnicion', models.IntegerField(blank=True, null=True, verbose_name='Tiempo fuente ignición (s)')),
                ('resultado', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True, verbose_name='Clase combustión')),
                ('fechaInicio', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fechaFin', models.DateField(blank=True, null=True, verbose_name='FechaFin')),
                ('fechaAuto', models.DateField(auto_now_add=True, verbose_name='Fecha automática')),
                ('fechaRev', models.DateField(auto_now=True, verbose_name='Fecha revisión')),
                ('observacion', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion')),
                ('horasEnsayo', models.DecimalField(decimal_places=2, default=3, max_digits=5, verbose_name='Tiempo de ensayo')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.listaensayos', verbose_name='Ensayo')),
                ('equipos', models.ManyToManyField(to='calidad.equipos', verbose_name='Equipos')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.muestras', verbose_name='Muestra')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'BZ',
                'verbose_name_plural': 'BZ',
            },
        ),
    ]
