# Generated by Django 4.2.7 on 2025-09-19 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0043_alter_clo_cerillas_alter_pmax_cerillas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadostmin',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'),
        ),
    ]
