# Generated by Django 4.2.7 on 2024-09-14 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0043_remove_n4_celda_n4_celda100_n4_celda25'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='n4',
            name='celda100',
        ),
        migrations.RemoveField(
            model_name='n4',
            name='celda25',
        ),
    ]
