# Generated by Django 4.2.7 on 2026-02-18 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0044_alter_o1_friable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o1',
            name='friable',
            field=models.CharField(blank=True, choices=[('1', 'Si'), ('2', 'No')], max_length=50, null=True, verbose_name='Friable'),
        ),
    ]
