# Generated by Django 4.2.7 on 2024-09-14 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0044_remove_n4_celda100_remove_n4_celda25'),
    ]

    operations = [
        migrations.AddField(
            model_name='n4',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', 'No se clasifica'), ('2', 'Grupo embalaje/envasado II/Categoría 1 '), ('3', 'Exenta si se transporta en bultos <3 m3'), ('4', 'Grupo embalaje/envasado III/Categoría 2')], max_length=100, null=True, verbose_name='resultado'),
        ),
    ]
