# Generated by Django 4.2.7 on 2026-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0044_alter_explonoexplo_horasensayo_bz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bz',
            name='horasEnsayo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='Tiempo de ensayo'),
        ),
    ]
