# Generated by Django 4.2.7 on 2026-06-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0045_alter_bz_horasensayo'),
    ]

    operations = [
        migrations.AddField(
            model_name='bz',
            name='tipoIgnicion',
            field=models.CharField(blank=True, choices=[('1', 'Sin ignición'), ('2', 'Breve ignición, extinción rápida'), ('3', 'Combustión localizada o brasa menor de 40 mm'), ('4', 'Brasa sin chispas o descomposición lenta sin llama'), ('5', 'Chisporroteo o combustión lenta con llama'), ('6', 'Combustión muy rápida con llama o descomposición sin llama')], max_length=100, null=True, verbose_name='Tipo ignición'),
        ),
    ]
