# Generated by Django 4.2.7 on 2024-09-20 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0045_n4_resultado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resultadosn4',
            old_name='tconsigna',
            new_name='tConsigna',
        ),
        migrations.AlterField(
            model_name='resultadosn4',
            name='celda',
            field=models.CharField(choices=[('1', '25 mm'), ('2', '100 mm')], max_length=300, verbose_name='Celdas'),
        ),
    ]
