# Generated by Django 4.2.7 on 2026-02-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0045_alter_o1_friable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='o1',
            name='friable',
            field=models.CharField(blank=True, choices=[('1', 'NO'), ('2', 'SI')], max_length=50, null=True, verbose_name='Friable'),
        ),
        migrations.AlterField(
            model_name='o1',
            name='humedadCelulosa',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Humedad Celulosa'),
        ),
    ]
