# Generated by Django 4.2.7 on 2026-07-01 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0046_bz_tipoignicion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bz',
            name='temperaturaEnsayo',
        ),
        migrations.CreateModel(
            name='ResultadosBz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperaturaEnsayo', models.IntegerField(verbose_name='Temperatura de ensayo')),
                ('tipoIgnicion', models.CharField(blank=True, choices=[('1', 'Sin ignición'), ('2', 'Breve ignición, extinción rápida'), ('3', 'Combustión localizada o brasa menor de 40 mm'), ('4', 'Brasa sin chispas o descomposición lenta sin llama'), ('5', 'Chisporroteo o combustión lenta con llama'), ('6', 'Combustión muy rápida con llama o descomposición sin llama')], max_length=100, null=True, verbose_name='Tipo ignición')),
                ('resultado', models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, null=True, verbose_name='Clase combustión')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.bz', verbose_name='Ensayo BZ')),
            ],
            options={
                'verbose_name': 'Resultado BZ',
                'verbose_name_plural': 'Resultados BZ',
            },
        ),
    ]
