# Generated by Django 4.2.7 on 2024-09-20 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0046_rename_tconsigna_resultadosn4_tconsigna_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='n4',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='humedad',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Humedad Ambiente'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='observacion',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Observacion'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', 'No se clasifica'), ('2', 'Grupo embalaje/envasado II/Categoría 1 '), ('3', 'Exenta si se transporta en bultos <3 m3'), ('4', 'Grupo embalaje/envasado III/Categoría 2'), ('5', 'Exenta si se transporta en bultos <450 litros')], max_length=100, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='n4',
            name='temperaturaAmbiente',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura Ambiente'),
        ),
    ]
