# Generated by Django 4.2.7 on 2026-07-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0047_remove_bz_temperaturaensayo_resultadosbz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bz',
            name='nRepeticiones',
        ),
        migrations.AddField(
            model_name='resultadosbz',
            name='nRepeticiones',
            field=models.IntegerField(blank=True, default=10, null=True, verbose_name='Número repeticiones'),
        ),
        migrations.AlterField(
            model_name='bz',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True, verbose_name='Clase combustión'),
        ),
        migrations.AlterField(
            model_name='resultadosbz',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=100, null=True, verbose_name='Clase combustión'),
        ),
    ]
