# Generated by Django 4.2.7 on 2024-09-24 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0048_o1_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultadoso1',
            name='tiempo',
        ),
        migrations.CreateModel(
            name='TiemposO1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.IntegerField(verbose_name='Tiempo')),
                ('resultados', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ensayos.resultadoso1', verbose_name='Resultado')),
            ],
        ),
    ]
