# Generated by Django 4.2.7 on 2024-09-24 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0049_remove_resultadoso1_tiempo_tiemposo1'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoso1',
            name='tiempo1',
            field=models.IntegerField(default=0, verbose_name='Tiempo1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoso1',
            name='tiempo2',
            field=models.IntegerField(default=0, verbose_name='Tiempo2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoso1',
            name='tiempo3',
            field=models.IntegerField(default=0, verbose_name='Tiempo3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoso1',
            name='tiempo4',
            field=models.IntegerField(default=0, verbose_name='Tiempo4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resultadoso1',
            name='tiempo5',
            field=models.IntegerField(default=0, verbose_name='Tiempo5'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TiemposO1',
        ),
    ]
