# Generated by Django 4.2.7 on 2025-02-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0051_alter_o1_ensayohumedad_alter_o1_fecha_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='granulometria',
            name='archivo',
            field=models.FileField(default='null', upload_to='media/archivosGranulometria'),
            preserve_default=False,
        ),
    ]
