# Generated by Django 4.2.7 on 2025-02-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0052_granulometria_archivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='granulometria',
            name='observacion',
            field=models.CharField(blank=True, default='null', max_length=1000, null=True, verbose_name='Observacion'),
        ),
    ]
