# Generated by Django 4.2.7 on 2025-02-19 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0054_remove_granulometria_observacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='granulometria',
            name='archivo',
            field=models.FileField(upload_to='archivosGranulometria'),
        ),
        migrations.AlterField(
            model_name='resultadosemi',
            name='concentracion',
            field=models.IntegerField(verbose_name='Concentracion'),
        ),
    ]
