# Generated by Django 4.2.7 on 2025-02-19 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0055_alter_granulometria_archivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosemi',
            name='energia',
            field=models.IntegerField(verbose_name='Energia'),
        ),
        migrations.AlterField(
            model_name='resultadosemi',
            name='retardo',
            field=models.IntegerField(verbose_name='Retardo'),
        ),
    ]
