# Generated by Django 4.2.7 on 2025-02-19 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0056_alter_resultadosemi_energia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emi',
            name='presion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='Presión Ambiente'),
        ),
    ]
