# Generated by Django 4.2.7 on 2025-02-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0059_alter_resultadosemi_numeroensayo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosrec',
            name='resultado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Resultado'),
        ),
    ]
