# Generated by Django 4.2.7 on 2025-02-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0060_alter_resultadosrec_resultado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadosrec',
            name='tension',
            field=models.IntegerField(blank=True, null=True, verbose_name='Resultado'),
        ),
    ]
