# Generated by Django 4.2.7 on 2025-03-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ensayos', '0063_alter_resultadosn4_tconsigna'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultadostmic',
            name='resultado',
            field=models.CharField(blank=True, choices=[('1', 'SI'), ('2', 'NO'), ('3', 'FUNDE'), ('4', 'NO FUNDE')], max_length=300, null=True, verbose_name='resultado'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tMaxima',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tPlato',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Temperatura plato'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoPrueba',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo ensayo'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tiempoTmax',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Tiempo a temperatura máxima'),
        ),
        migrations.AlterField(
            model_name='resultadostmic',
            name='tipoIgnicion',
            field=models.CharField(blank=True, choices=[('1', 'VISUAL'), ('2', 'TERMOPAR'), ('3', 'VISUAL/TERMOPAR')], max_length=300, null=True, verbose_name='Tipo ignición'),
        ),
    ]
