# Generated by Django 4.2.7 on 2025-03-06 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0015_rename_tamaño_descripcionmuestra_tamano'),
        ('ensayos', '0064_alter_resultadostmic_resultado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tratamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secado', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=500, verbose_name='Secado')),
                ('fechaSecadoInicio', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fechaSecadoFin', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('molido', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=500, verbose_name='Molido')),
                ('fechaMolidoInicio', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fechaMolidoFin', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('tamizado', models.CharField(choices=[('1', 'SI'), ('2', 'NO')], max_length=500, verbose_name='Tamizado')),
                ('fechaTamizadoInicio', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('fechaTamizadoFin', models.DateField(blank=True, null=True, verbose_name='Fecha')),
                ('horasEnsayo', models.DecimalField(decimal_places=2, default=5, max_digits=5, verbose_name='Tiempo de ensayo')),
                ('ensayo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.listaensayos', verbose_name='Ensayo')),
                ('equipoMolido', models.ManyToManyField(related_name='tratamientos_equipoMolido', to='ensayos.equipos', verbose_name='Equipos de molienda')),
                ('equipoSecado', models.ManyToManyField(related_name='tratamientos_equipoSecado', to='ensayos.equipos', verbose_name='Equipos de secado')),
                ('equipoTamizado', models.ManyToManyField(related_name='tratamientos_equipoTamizado', to='ensayos.equipos', verbose_name='Equipos de tamizado')),
                ('muestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.muestras', verbose_name='Muestra')),
            ],
            options={
                'verbose_name': 'Tratamiento',
                'verbose_name_plural': 'Tratamientos',
            },
        ),
    ]
