# Generated by Django 4.2.4 on 2023-10-24 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DescripcionMuestra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=300, verbose_name='Descripcion')),
                ('etiquetado', models.CharField(choices=[('etiqueta', 'etiqueta'), ('rotulacion', 'rotulacion'), ('sin etiqueta', 'sin etiqueta')], max_length=300, verbose_name='Etiquetado')),
                ('envolturaExt', models.CharField(max_length=300, verbose_name='Envoltura exterior')),
                ('envolturaInt', models.CharField(max_length=300, verbose_name='Envoltura interior')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Peso')),
                ('procedencia', models.CharField(max_length=300, verbose_name='Procedencia')),
                ('estadoEnvio', models.CharField(max_length=300, verbose_name='Estado del envío')),
                ('aspectoMuestra', models.CharField(max_length=300, verbose_name='Aspecto de la muestra')),
                ('color', models.CharField(max_length=300, verbose_name='Color')),
                ('brillo', models.CharField(max_length=300, verbose_name='Brillo')),
                ('tamaño', models.CharField(max_length=300, verbose_name='Tamaño aparente')),
                ('homogeneidad', models.CharField(max_length=300, verbose_name='Homogeneidad')),
                ('formaEnsayo', models.CharField(choices=[('S/V', 'S/V'), ('Preparada', 'Preparada')], max_length=300, verbose_name='¿Como se ensaya?')),
                ('observacion', models.TextField(verbose_name='observaciones')),
            ],
            options={
                'verbose_name': 'Descripcion muestra',
                'verbose_name_plural': 'Descripciones Muestras',
            },
        ),
        migrations.CreateModel(
            name='ListaEnsayos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ensayo', models.CharField(max_length=300, verbose_name='Ensayo')),
                ('normativa', models.CharField(max_length=300, verbose_name='Normativa')),
                ('poens', models.CharField(max_length=300, verbose_name='POENS')),
            ],
            options={
                'verbose_name': 'Lista Ensayo',
                'verbose_name_plural': 'Listas Ensayos',
            },
        ),
        migrations.CreateModel(
            name='Muestras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeroMuestra', models.IntegerField(verbose_name='Número de muestras')),
                ('fecha', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('fechaRevision', models.DateField(blank=True, null=True, verbose_name='Fecha revisión')),
                ('descripcionMuestra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='muestras.descripcionmuestra', verbose_name='Descripción Muestra')),
                ('expediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expedientes.expedientes', verbose_name='Expediente')),
                ('listaEnsayos', models.ManyToManyField(to='muestras.listaensayos', verbose_name='Ensayos')),
            ],
            options={
                'verbose_name': 'Muestra',
                'verbose_name_plural': 'Muestras',
            },
        ),
    ]
