# Generated by Django 4.2.4 on 2023-10-25 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionmuestra',
            name='imagenEnvoltorio',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesMuestras'),
        ),
        migrations.AddField(
            model_name='descripcionmuestra',
            name='imagenMuestra',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesMuestras'),
        ),
    ]
