# Generated by Django 4.2.4 on 2023-10-25 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0002_descripcionmuestra_imagenenvoltorio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='descripcionmuestra',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='muestras',
            name='descripcionMuestra',
        ),
        migrations.AddField(
            model_name='descripcionmuestra',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='muestras.muestras', verbose_name='Muestra'),
        ),
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='imagenEnvoltorio',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesMuestras', verbose_name='Imagen envoltorio'),
        ),
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='imagenMuestra',
            field=models.ImageField(blank=True, null=True, upload_to='imagenesMuestras', verbose_name='Imagen muestra'),
        ),
    ]
