# Generated by Django 4.2.7 on 2025-06-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_listaensayos_orden'),
    ]

    operations = [
        migrations.AddField(
            model_name='listaensayos',
            name='fechaAprobacion',
            field=models.DateField(default='2025-07-10', verbose_name='Fecha aprobación'),
            preserve_default=False,
        ),
    ]
