# Generated by Django 4.2.4 on 2023-10-26 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0003_remove_descripcionmuestra_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='muestras',
            name='numeroMuestra',
        ),
    ]
