# Generated by Django 4.2.7 on 2025-10-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_listaensayos_fechaaprobacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionmuestra',
            name='empresaTransporte',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Empresa transportes'),
        ),
        migrations.AddField(
            model_name='descripcionmuestra',
            name='humedadAparente',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Humedad aparente'),
        ),
    ]
