# Generated by Django 4.2.4 on 2023-10-26 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0004_remove_muestras_numeromuestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestras',
            name='fechaComienzo',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha comienzo ensayos'),
        ),
    ]
