# Generated by Django 4.2.4 on 2023-10-26 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0005_muestras_fechacomienzo'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestras',
            name='id_muestra',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero muestra'),
        ),
    ]
