# Generated by Django 4.2.7 on 2025-10-22 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0005_descripcionmuestra_empresatransporte_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='empresaTransporte',
            field=models.CharField(default='-', max_length=300, verbose_name='Empresa transportes'),
        ),
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='humedadAparente',
            field=models.CharField(default='-', max_length=300, verbose_name='Humedad aparente'),
        ),
    ]
