# Generated by Django 4.2.4 on 2023-10-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_expedientes_nmuestras'),
        ('muestras', '0006_muestras_id_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestras',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='expedientes.empresa', verbose_name='Empresa'),
        ),
    ]
