# Generated by Django 4.2.4 on 2023-12-28 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0008_muestras_observaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionmuestra',
            name='documentación',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=300, null=True, verbose_name='Documentación'),
        ),
        migrations.AddField(
            model_name='descripcionmuestra',
            name='fecha_recepcion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha recepción'),
        ),
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='muestra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='descripcionmuestra', to='muestras.muestras', verbose_name='Muestra'),
        ),
    ]
