# Generated by Django 4.2.4 on 2023-12-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0009_descripcionmuestra_documentación_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='descripcionmuestra',
            name='id_fabricante',
            field=models.CharField(blank=True, choices=[('Si', 'Si'), ('No', 'No')], max_length=300, null=True, verbose_name='Identificación fabricante'),
        ),
    ]
