# Generated by Django 4.1 on 2024-01-05 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0011_alter_descripcionmuestra_id_fabricante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descripcionmuestra',
            name='peso',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Peso'),
        ),
    ]
