# Generated by Django 4.2.7 on 2024-01-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0012_alter_descripcionmuestra_peso'),
    ]

    operations = [
        migrations.AddField(
            model_name='muestras',
            name='estado',
            field=models.CharField(choices=[('1', 'Esperando muestra'), ('2', 'Parada'), ('3', 'Ensayando'), ('4', 'Por revisar'), ('5', 'Terminada')], default='1', max_length=300, verbose_name='Estado'),
        ),
    ]
