# Generated by Django 4.2.4 on 2024-01-16 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0013_muestras_estado'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descripcionmuestra',
            old_name='documentación',
            new_name='documentacion',
        ),
    ]
