# Generated by Django 4.2.4 on 2024-01-16 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muestras', '0014_rename_documentación_descripcionmuestra_documentacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='descripcionmuestra',
            old_name='tamaño',
            new_name='tamano',
        ),
    ]
