# Generated by Django 4.2.4 on 2023-10-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientes',
            name='nMuestras',
            field=models.IntegerField(blank=True, null=True, verbose_name='Numero de muestras'),
        ),
    ]
