# Generated by Django 4.2.7 on 2025-04-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0002_expedientes_porcentaje'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Porcentaje ensayado'),
        ),
    ]
