# Generated by Django 4.2.7 on 2025-09-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_expedientes_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientes',
            name='empresaContrata',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Empresa subcontrata'),
        ),
    ]
