# Generated by Django 4.2.7 on 2025-06-11 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0003_alter_expedientes_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='expedientes',
            name='empresaContrata',
            field=models.CharField(default='', max_length=300, verbose_name='Empresa subcontratada'),
        ),
    ]
