# Generated by Django 4.2.7 on 2025-06-11 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0004_expedientes_empresacontrata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='empresaContrata',
            field=models.CharField(default='', max_length=300, verbose_name='Empresa subcontrata'),
        ),
    ]
