# Generated by Django 4.2.7 on 2025-09-16 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expedientes', '0005_alter_expedientes_empresacontrata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedientes',
            name='empresaContrata',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='Empresa subcontrata'),
        ),
    ]
